server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/deal

internal:
  service:
    calculator:
      url: ${SERVICE_URL}

spring:
  application:
    name: Deal
  jackson:
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
