services:
  calculator-service:
    image: ghcr.io/lofominhili/neobank:latest
    container_name: calculator
    restart: on-failure
    environment:
      SERVER_PORT: ${SERVER_PORT}
      LOAN_BASE_RATE: ${LOAN_BASE_RATE}
      LOAN_INSURANCE_DISCOUNT: ${LOAN_INSURANCE_DISCOUNT}
      LOAN_SALARY_CLIENT_DISCOUNT: ${LOAN_SALARY_CLIENT_DISCOUNT}
      LOAN_INSURANCE_COST: ${LOAN_INSURANCE_COST}