name: cd
run-name: Workflow ${{ github.workflow }} triggered by @${{ github.actor }}
on:
  push:
    branches:
      - develop
jobs:
  build-image:
    name: build-image
    runs-on: ubuntu-22.04
    steps:
      - name: Pull git repository
        uses: actions/checkout@v4.1.5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: Calculator/
          push: true
          tags: ghcr.io/lofominhili/neobank:latest